const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Platform,
		C3.Plugins.TiledBg,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.TiledBg.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Cnds.CompareX
	];
};
self.C3_JsPropNameTable = [
	{Var: 0},
	{Sine: 0},
	{Sine2: 0},
	{Text: 0},
	{numberT: 0},
	{Text2: 0},
	{var: 0},
	{Текст: 0},
	{Anchor: 0},
	{back: 0},
	{frame: 0},
	{vk: 0},
	{A: 0},
	{skins: 0},
	{coinsTEXT: 0},
	{skins2: 0},
	{Pin: 0},
	{center2: 0},
	{point: 0},
	{BotPoint: 0},
	{soid: 0},
	{bot: 0},
	{LastY: 0},
	{Collision: 0},
	{Rotate: 0},
	{Platform: 0},
	{Frog: 0},
	{luoi: 0},
	{root: 0},
	{Таймер: 0},
	{Fly: 0},
	{bestICON: 0},
	{playBUTTON: 0},
	{latestICON: 0},
	{latestTEXT: 0},
	{bestTEXT: 0},
	{number: 0},
	{Timer: 0},
	{Sprite: 0},
	{info: 0},
	{shop: 0},
	{soundBUTTON: 0},
	{Якорь: 0},
	{delits: 0},
	{invate: 0},
	{replayBUTTON: 0},
	{scoreTEXT: 0},
	{botton: 0},
	{Sprite4: 0},
	{xz: 0},
	{Sprite7: 0},
	{Пуля: 0},
	{Поворот: 0},
	{asteroids: 0},
	{Угасание: 0},
	{name: 0},
	{planets: 0},
	{clu: 0},
	{word: 0},
	{table: 0},
	{Тач: 0},
	{ЛокальноеХранилище: 0},
	{Браузер: 0},
	{Аудио: 0},
	{Shop_Array: 0},
	{record: 0},
	{Спрайт: 0},
	{GamePush: 0},
	{Спрайт2: 0},
	{Family1: 0},
	{best: 0},
	{latest: 0},
	{score: 0},
	{start: 0},
	{CreateFly: 0},
	{rollshake: 0},
	{shake: 0},
	{gameover: 0},
	{crYPoint: 0},
	{crXpoint: 0},
	{fall: 0},
	{CheckPoint: 0},
	{du: 0},
	{move: 0},
	{change: 0},
	{bannerTimer: 0},
	{deadM: 0},
	{vkl: 0},
	{planet: 0},
	{asteroid: 0},
	{ads: 0},
	{audio: 0},
	{select_skins: 0},
	{coins: 0}
];

self.InstanceType = {
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Текст: class extends self.ITextInstance {},
	back: class extends self.ISpriteInstance {},
	frame: class extends self.ISpriteInstance {},
	vk: class extends self.ISpriteInstance {},
	skins: class extends self.ISpriteInstance {},
	coinsTEXT: class extends self.ISpriteFontInstance {},
	skins2: class extends self.ISpriteInstance {},
	center2: class extends self.ISpriteInstance {},
	point: class extends self.ISpriteInstance {},
	BotPoint: class extends self.ISpriteInstance {},
	soid: class extends self.ISpriteInstance {},
	bot: class extends self.ISpriteInstance {},
	Frog: class extends self.ISpriteInstance {},
	root: class extends self.ITiledBackgroundInstance {},
	Fly: class extends self.ISpriteInstance {},
	bestICON: class extends self.ISpriteInstance {},
	playBUTTON: class extends self.ISpriteInstance {},
	latestICON: class extends self.ISpriteInstance {},
	latestTEXT: class extends self.ISpriteFontInstance {},
	bestTEXT: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	shop: class extends self.ISpriteInstance {},
	soundBUTTON: class extends self.ISpriteInstance {},
	delits: class extends self.ISpriteInstance {},
	invate: class extends self.ISpriteInstance {},
	replayBUTTON: class extends self.ISpriteInstance {},
	scoreTEXT: class extends self.ISpriteFontInstance {},
	botton: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	xz: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	asteroids: class extends self.ISpriteInstance {},
	name: class extends self.ISpriteInstance {},
	planets: class extends self.ISpriteInstance {},
	clu: class extends self.ISpriteInstance {},
	word: class extends self.ISpriteInstance {},
	table: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	Браузер: class extends self.IInstance {},
	Аудио: class extends self.IInstance {},
	Shop_Array: class extends self.IArrayInstance {},
	record: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	GamePush: class extends self.IInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {}
}