const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.Pin,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.LocalStorage,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Eponesh_GameScore.Exps.Language,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.objectcount,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderClose,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.Text.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{trigger1: 0},
	{trigger2: 0},
	{trigger3: 0},
	{trigger4: 0},
	{trigger5: 0},
	{trigger6: 0},
	{trigger7: 0},
	{trigger8: 0},
	{Anchor: 0},
	{BannerWin: 0},
	{Work: 0},
	{Pin: 0},
	{BIGLINE: 0},
	{BIGLINE2: 0},
	{block2: 0},
	{BOT: 0},
	{Boost: 0},
	{GameScore: 0},
	{LiteTween: 0},
	{info: 0},
	{invate: 0},
	{Move: 0},
	{Line: 0},
	{LocalStorage: 0},
	{Line2: 0},
	{Якорь: 0},
	{logo: 0},
	{BigMove: 0},
	{SpeedBoost: 0},
	{Прикрепить: 0},
	{mask: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Player: 0},
	{post: 0},
	{NumberPoint: 0},
	{POINT: 0},
	{Синусоида: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{IDText: 0},
	{Синусоид: 0},
	{Синусоид2: 0},
	{SpriteFont: 0},
	{table: 0},
	{Text6: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Touch: 0},
	{TiledBackground4: 0},
	{Аудио: 0},
	{masklogo: 0},
	{Спрайт: 0},
	{BotAndYPoint: 0},
	{NameAddPoint: 0},
	{FpsScore: 0},
	{BigLinePoint1Y: 0},
	{BigLinePoint1X: 0},
	{BigLinePoint2Y: 0},
	{BigLinePoint2X: 0},
	{RecordY: 0},
	{BIGMOVE: 0},
	{DestroyedPlayer: 0},
	{GlobalOpacity: 0},
	{VariableMove: 0},
	{ResultFrameWork: 0},
	{VisorWindow: 0},
	{LinePositionY: 0},
	{VisorLinePositionY: 0},
	{speed: 0},
	{speed2: 0},
	{spawn: 0},
	{spawnY: 0},
	{spawnY2: 0},
	{Dollars: 0},
	{tmads: 0}
];

self.InstanceType = {
	trigger1: class extends self.ITiledBackgroundInstance {},
	trigger2: class extends self.ITiledBackgroundInstance {},
	trigger3: class extends self.ITiledBackgroundInstance {},
	trigger4: class extends self.ITiledBackgroundInstance {},
	trigger5: class extends self.ITiledBackgroundInstance {},
	trigger6: class extends self.ITiledBackgroundInstance {},
	trigger7: class extends self.ITiledBackgroundInstance {},
	trigger8: class extends self.ITiledBackgroundInstance {},
	BannerWin: class extends self.ISpriteInstance {},
	BIGLINE: class extends self.ITiledBackgroundInstance {},
	BIGLINE2: class extends self.ITiledBackgroundInstance {},
	block2: class extends self.ISpriteInstance {},
	BOT: class extends self.ISpriteInstance {},
	Boost: class extends self.ISpriteInstance {},
	GameScore: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	info: class extends self.ISpriteInstance {},
	invate: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	Line2: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	mask: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	post: class extends self.ISpriteInstance {},
	POINT: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	table: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Аудио: class extends self.IInstance {},
	masklogo: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {}
}