const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Function,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.SetWidth,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Behaviors.Physics.Cnds.IsSleeping,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderStart,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.Browser.Acts.Reload,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Pin: 0},
	{PinPart_2: 0},
	{PinPart_1: 0},
	{PinBack2: 0},
	{PinBack1: 0},
	{Point_0: 0},
	{Point_1: 0},
	{MoveToPoint: 0},
	{Speed: 0},
	{Physics: 0},
	{DestroyOutsideLayout: 0},
	{Red: 0},
	{Pink: 0},
	{Green: 0},
	{Black: 0},
	{Blue: 0},
	{Yellow: 0},
	{LCount: 0},
	{BlackSpawner: 0},
	{BlueSpawner: 0},
	{GreenSpawner: 0},
	{YellowSpawner: 0},
	{PinkSpawner: 0},
	{RedSpawner: 0},
	{BtnBack: 0},
	{BtnMoreGames: 0},
	{BtnHome: 0},
	{BtnRestart: 0},
	{BtnSounds: 0},
	{BtnPlay: 0},
	{LevelButton: 0},
	{Sine: 0},
	{Label: 0},
	{LevelFont: 0},
	{LevelLabel: 0},
	{Logo: 0},
	{Manual: 0},
	{Fade: 0},
	{BlackScreen: 0},
	{TouchSprite: 0},
	{Particles: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Particles5: 0},
	{Particles6: 0},
	{Shadow: 0},
	{SolidObject: 0},
	{Initial_X: 0},
	{Vector: 0},
	{isFull: 0},
	{AllDropsCount: 0},
	{CollectedDropsCount: 0},
	{WheelsSpeed: 0},
	{Truck: 0},
	{TruckSensor: 0},
	{Wall: 0},
	{Rotate: 0},
	{Wheel_1: 0},
	{Wheel_2: 0},
	{Wheel_3: 0},
	{Keyboard: 0},
	{Touch: 0},
	{Function: 0},
	{Browser: 0},
	{Array: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{GamePush: 0},
	{Sprite: 0},
	{isGame: 0},
	{Level: 0},
	{LostDropsCount: 0},
	{ads: 0},
	{isSoundsActive: 0}
];

self.InstanceType = {
	PinPart_2: class extends self.ISpriteInstance {},
	PinPart_1: class extends self.ISpriteInstance {},
	PinBack2: class extends self.ISpriteInstance {},
	PinBack1: class extends self.ISpriteInstance {},
	Pin: class extends self.ISpriteInstance {},
	Red: class extends self.ISpriteInstance {},
	Pink: class extends self.ISpriteInstance {},
	Green: class extends self.ISpriteInstance {},
	Black: class extends self.ISpriteInstance {},
	Blue: class extends self.ISpriteInstance {},
	Yellow: class extends self.ISpriteInstance {},
	BlackSpawner: class extends self.ISpriteInstance {},
	BlueSpawner: class extends self.ISpriteInstance {},
	GreenSpawner: class extends self.ISpriteInstance {},
	YellowSpawner: class extends self.ISpriteInstance {},
	PinkSpawner: class extends self.ISpriteInstance {},
	RedSpawner: class extends self.ISpriteInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	BtnMoreGames: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnSounds: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	LevelButton: class extends self.ISpriteInstance {},
	Label: class extends self.ISpriteInstance {},
	LevelFont: class extends self.ISpriteFontInstance {},
	LevelLabel: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	Manual: class extends self.ISpriteInstance {},
	BlackScreen: class extends self.ISpriteInstance {},
	TouchSprite: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Shadow: class extends self.ISpriteInstance {},
	SolidObject: class extends self.ISpriteInstance {},
	Truck: class extends self.ISpriteInstance {},
	TruckSensor: class extends self.ISpriteInstance {},
	Wall: class extends self.ISpriteInstance {},
	Wheel_1: class extends self.ISpriteInstance {},
	Wheel_2: class extends self.ISpriteInstance {},
	Wheel_3: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	Sprite: class extends self.ISpriteInstance {}
}