const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.Fade,
		C3.Behaviors.Platform,
		C3.Plugins.Arr,
		C3.Behaviors.Anchor,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Sin,
		C3.Plugins.Function,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowPreloader,
		C3.Plugins.System.Cnds.IsNaN,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetCharacterSpacing,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.Every
	];
};
self.C3_JsPropNameTable = [
	{ScrollTo: 0},
	{Sprite: 0},
	{Block_destroy: 0},
	{ID: 0},
	{Solid: 0},
	{Fade: 0},
	{Block: 0},
	{Position: 0},
	{Platform: 0},
	{Hero: 0},
	{Gen: 0},
	{Sprite2: 0},
	{Anchor: 0},
	{Black_ugly: 0},
	{Touch: 0},
	{Block_spawn: 0},
	{Y_lerp: 0},
	{SpriteFont: 0},
	{Pin: 0},
	{SpriteFont2: 0},
	{X_lerp: 0},
	{Restart: 0},
	{leaderboardsComplex: 0},
	{pointer: 0},
	{question: 0},
	{Audio: 0},
	{Sprite3: 0},
	{SpriteFont3: 0},
	{Sprite4: 0},
	{Block_back: 0},
	{Text: 0},
	{logo: 0},
	{LiteTween: 0},
	{Text2: 0},
	{highscore: 0},
	{Sine: 0},
	{Text3: 0},
	{Text4: 0},
	{block2: 0},
	{Text6: 0},
	{Text7: 0},
	{touch2: 0},
	{strelka: 0},
	{newRecord: 0},
	{Function: 0},
	{Particles: 0},
	{Particles2: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Particles3: 0},
	{FireWork: 0},
	{FireWork2: 0},
	{amazing: 0},
	{Particles4: 0},
	{tap: 0},
	{Спрайт: 0},
	{GamePush: 0},
	{wkala: 0},
	{Random_next: 0},
	{Game_sys: 0},
	{Y_des: 0},
	{Score: 0},
	{Score_smen: 0},
	{ID_old: 0},
	{ID_old_znac: 0},
	{Gen_visota: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	Hero: class extends self.ISpriteInstance {},
	Gen: class extends self.IArrayInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Black_ugly: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Block_spawn: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	Restart: class extends self.ISpriteInstance {},
	leaderboardsComplex: class extends self.ISpriteInstance {},
	pointer: class extends self.ISpriteInstance {},
	question: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Block_back: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	logo: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	highscore: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	block2: class extends self.ISpriteInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {},
	touch2: class extends self.ISpriteInstance {},
	strelka: class extends self.ISpriteInstance {},
	newRecord: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Particles3: class extends self.IParticlesInstance {},
	FireWork: class extends self.IParticlesInstance {},
	FireWork2: class extends self.IParticlesInstance {},
	amazing: class extends self.ISpriteInstance {},
	Particles4: class extends self.IParticlesInstance {},
	tap: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	GamePush: class extends self.IInstance {}
}