const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Multiplayer,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Rotate,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.wrap,
		C3.Plugins.Timeline,
		C3.Plugins.TextBox,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Multiplayer.Acts.AddClientInputValue,
		C3.Plugins.Multiplayer.Acts.SyncObject2,
		C3.Plugins.Multiplayer.Acts.SyncObjectInstanceVar,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Multiplayer.Cnds.SignallingIsInRoom,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Multiplayer.Cnds.OnPeerConnected,
		C3.Plugins.Multiplayer.Cnds.IsHost,
		C3.Plugins.Multiplayer.Acts.AssociateObjectWithPeer,
		C3.Plugins.Multiplayer.Exps.MyID,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Multiplayer.Acts.SendPeerMessage,
		C3.Plugins.Multiplayer.Exps.FromAlias,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Multiplayer.Exps.MyAlias,
		C3.Plugins.Multiplayer.Exps.PeerAlias,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Rotate.Cnds.IsEnabled,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Multiplayer.Exps.HostAlias,
		C3.Plugins.Multiplayer.Exps.PeerIDAt,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Multiplayer.Acts.DisconnectRoom,
		C3.Plugins.Multiplayer.Acts.SignallingLeaveRoom,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerName,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Multiplayer.Cnds.SignallingIsConnected,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID,
		C3.Plugins.Multiplayer.Cnds.OnSignallingConnected,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.Multiplayer.Acts.SignallingAutoJoinRoom,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Plugins.Multiplayer.Exps.PeerCount,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Multiplayer.Cnds.IsSupported,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Multiplayer.Acts.SignallingJoinRoom,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Cnds.Repeat
	];
};
self.C3_JsPropNameTable = [
	{Тач: 0},
	{Multiplayer: 0},
	{GamePush: 0},
	{jump: 0},
	{results: 0},
	{Платформер: 0},
	{Поворот: 0},
	{gg: 0},
	{Твинанимация: 0},
	{btn_menu: 0},
	{score: 0},
	{Якорь: 0},
	{Search: 0},
	{id: 0},
	{gg2: 0},
	{Клавиатура: 0},
	{num: 0},
	{player_name: 0},
	{Mouse: 0},
	{Твёрдый: 0},
	{TiledBackground2: 0},
	{Scored: 0},
	{BottomPipe: 0},
	{TopPipe: 0},
	{Заворачивание: 0},
	{Спрайт: 0},
	{black: 0},
	{word: 0},
	{ВременнаяШкала: 0},
	{Спрайт2: 0},
	{TextInput: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Аудио: 0},
	{JumpStrength: 0},
	{SCROLLSPEED: 0},
	{SecondsPerObstacle: 0},
	{Score: 0},
	{namegg2: 0},
	{stolbX: 0},
	{stolbY: 0},
	{randoms: 0},
	{Nickname: 0},
	{Sec: 0},
	{Minuts: 0},
	{search: 0},
	{multyfriend: 0}
];

self.InstanceType = {
	Тач: class extends self.IInstance {},
	Multiplayer: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	gg: class extends self.ISpriteInstance {},
	btn_menu: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	Search: class extends self.ITextInstance {},
	gg2: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	player_name: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	BottomPipe: class extends self.ISpriteInstance {},
	TopPipe: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	black: class extends self.ISpriteInstance {},
	word: class extends self.ITextInstance {},
	ВременнаяШкала: class extends self.IInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Аудио: class extends self.IInstance {}
}